package uz.eloving.psychorotte

object Constants {
    fun islomga_davat():ArrayList<QuestionModel>{
        val question = ArrayList<QuestionModel>()
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi millat vakillari edilar ?",
            "Arab",
            "Fors",
            "Eron",
            "Hind",
            "Arab",
            "Tavrot va Injilda oxirgi zamon pay'ambari haqida keltirilgan !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi qabiladan edilar ?",
            "Quraysh",
            "Badaviy",
            "Umaviy",
            "Fotimiy",
            "Quraysh",
            "Payg'ambarimizga dushman bo'lgan qabila nomi !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi urug'dan edilar ?",
            "Bani Hoshim",
            "Bani Hamdon",
            "Bani Mazhij",
            "Bani Tayy",
            "Bani Hoshim",
            "Payg'ambarimiz bobolarining otalarini ismi bilan nomlangan !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qayerda tug'ilganlar ?",
            "Makka",
            "Madina",
            "Hirot",
            "Yaman",
            "Makka",
            "Kabatulloh joylashgan hudud !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) otalari ismi nima ?",
            "Abdulloh",
            "Hoshim",
            "Abu Tolib",
            "Hamza",
            "Abdulloh",
            "Allohning quli"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining ismi nima ?",
            "Abdulmuttalib",
            "Ibrohim",
            "Abu Tolib",
            "Hoshim",
            "Abdulmuttalib",
            "Bobolaridan so'ng Abu Tolib ismli tog'alari qaramog'ida qoldilar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining otalarini ismi nima ?",
            "Hoshim",
            "Ibrohim",
            "Abdulloh",
            "Abdulmuttalib",
            "Hoshim",
            "Payg'ambarimiz Muhammad (s.a.v) shu insonni urug'idan edilar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining bobolarini ismi nima ?",
            "Abdumannof",
            "Abdulloh",
            "Ibrohim",
            "Abdulmuttalib",
            "Abdumannof",
            "Ibrohim Xalilulloh Payg'ambarimizning uzoq shajarlari hisoblanadi !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi payg'ambarning avlodlaridan edilar ?",
            "Ibrohim Xalilulloh",
            "Muso a.s",
            "Iso masih",
            "Lut a.s",
            "Ibrohim Xalilulloh",
            "Iso a.s Payg'ambarimizga qarindosh emas edilar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) onalari ismi nima edi ?",
            "Omina",
            "Oisha",
            "Mariyam",
            "Osiyo",
            "Omina",
            "Osiyo Onamiz Firavinning ayollari edilar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) opa-singillari bo'lganmi, bo'lgan bo'lsa nechta ?",
            "Bo'lmagan",
            "1 ta",
            "2 ta",
            "3 ta",
            "Bo'lmagan",
            "Payg'ambarimiz otalaridan juda erta ajralganlar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) aka-ukalari bo'lganmi, bo'lgan bo'lsa nechta ?",
            "Bo'lmagan",
            "1 ta",
            "2 ta",
            "3 ta",
            "Bo'lmagan",
            "Payg'ambarimiz otalaridan juda erta ajralganlar !"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) otalari qachon vafot etdilar",
            "Payg'ambarimiz ona qornida 2 oyliklarida",
            "Payg'ambarimiz 6 yoshga to'lganlarida",
            "Payg'ambarimiz Hadicha onamizga uylanganda",
            "To'g'ri javob mavjud emas",
            "Payg'ambarimiz ona qornida 2 oyliklarida",
            "Payg'ambarimiz otalaridan juda erta ajralganlar !"
        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
        return question
    }
}