package uz.eloving.psychorotte

object Constants {
    fun islomga_davat():ArrayList<QuestionModel>{
        val question = ArrayList<QuestionModel>()
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi millat vakillari edilar ?",
            "Arab",
            "Fors",
            "Eron",
            "Hind",
            "Arab"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi qabiladan edilar ?",
            "Quraysh",
            "Badaviy",
            "Umaviy",
            "Fotimiy",
            "Quraysh"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi urug'dan edilar ?",
            "Bani Hoshim",
            "Bani Hamdon",
            "Bani Mazhij",
            "Bani Tayy",
            "Bani Hoshim"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qayerda tug'ilganlar ?",
            "Makka",
            "Madina",
            "Hirot",
            "Yaman",
            "Makka"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) otalari ismi nima ?",
            "Abdulloh",
            "Hoshim",
            "Abu Tolib",
            "Hamza",
            "Abdulloh"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining ismi nima ?",
            "Abdulmuttalib",
            "Ibrohim",
            "Abu Tolib",
            "Hoshim",
            "Abdulmuttalib"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining otalarini ismi nima ?",
            "Hoshim",
            "Ibrohim",
            "Abdulloh",
            "Abdulmuttalib",
            "Hoshim"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) bobolarining bobolarini ismi nima ?",
            "Abdumannof",
            "Abdulloh",
            "Ibrohim",
            "Abdulmuttalib",
            "Abdumannof"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) qaysi payg'ambarning avlodlaridan edilar ?",
            "Ibrohim Xalilulloh",
            "Muso a.s",
            "Iso masih",
            "Lut a.s",
            "Ibrohim Xalilulloh"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) onalari ismi nima edi ?",
            "Omina",
            "Oisha",
            "Mariyam",
            "Osiyo",
            "Omina"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) opa-singillari bo'lganmi, bo'lgan bo'lsa nechta ?",
            "Bo'lmagan",
            "1 ta",
            "2 ta",
            "3 ta",
            "Bo'lmagan"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) aka-ukalari bo'lganmi, bo'lgan bo'lsa nechta ?",
            "Bo'lmagan",
            "1 ta",
            "2 ta",
            "3 ta",
            "Bo'lmagan"
        ))
        question.add(QuestionModel(
            "Payg'ambarimiz Muhammad (s.a.v) otalari qachon vafot etdilar",
            "Payg'ambarimiz ona qornida 2 oyliklarida",
            "Payg'ambarimiz 6 yoshga to'lganlarida",
            "Payg'ambarimiz Hadicha onamizga uylanganda",
            "To'g'ri javob mavjud emas",
            "Payg'ambarimiz ona qornida 2 oyliklarida"
        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
//        question.add(QuestionModel(
//            "",
//            "",
//            "",
//            "",
//            "",
//            ""
//        ))
        return question
    }
}